### ISSUE TITLE
RECONOCIMIENTO GPS CON A-FRAME EN REALIDAD AUMENTADA

### ISSUE THREAD

**Issue by MariaJose-1007** [SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-equipo-magaly#1]
[RECONOCIMIENTO GPS CON A-FRAME EN REALIDAD AUMENTADA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-equipo-magaly/files/15203755/RECONOCIMIENTO.GPS.CON.A-FRAME.EN.REALIDAD.AUMENTADA.pdf)

**Comment by EdwinOrtiz1412** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado
